### ISSUE TITLE
lrecl invalid for demo.txt

### ISSUE THREAD

**Issue by philippe-richard** [zorts/hello_world#6]
file allocate_sh should be changed for the allocation of demo.txt, and assign an lrecl > 259 (for instance 286), otherwise script to_pds.sh will get an error 
SPARKID:/u/sparkid/hello_world/hello_world: >./to_pds.sh
cp: FSUM6260 write error on file "//'SPARKID.DEMO.TXT(README)'": EDC5003I Truncation of a record occurred during an I/O operation.
==================================
#!/bin/env bash

tso 'alloc da(demo.h) recfm(f b) lrecl(80) blksize(0) dir(1) track space(2 2)'
tso 'alloc da(demo.c) recfm(f b) lrecl(80) blksize(0) dir(1) track space(2 2)'
tso 'alloc da(demo.txt) recfm(v b) lrecl(259) blksize(0) dir(1) track space(2 2)'

**Comment by zorts** [comment]
Closing as permanent restriction.

**Comment by philippe-richard** [comment]
why did you close my 'issue' as permanent restriction ?
i had a pb with the sample file allocate_sh: it  should be changed for the allocation of demo.txt, and assign an lrecl > 259 (for instance 2860), otherwise script to_pds.sh will get an error
SPARKID:/u/sparkid/hello_world/hello_world: >./to_pds.sh
cp: FSUM6260 write error on file "//'SPARKID.DEMO.TXT(README)'": EDC5003I Truncation of a record occurred during an I/O operation.

**Comment by zorts** [comment]
As noted in Pull Request #7 that addresses this issue, I have a good reason for wanting to keep the LRECL at its present size. I was able to address the failure you reported by altering the content of README.md in a way that doesn't affect the presentation but still allows the file to be edited with ISPF.

Also - you are certainly welcome to fork the repo and make any changes you wish in your own fork. :-)

**Comment by philippe-richard** [comment]
you are certainly welcome to fork the repo and make any changes you wish in your own fork. :-)
i will have to, otherwise ./to_pds.sh will fail with
cp: FSUM6260 write error on file "//'SPARKID.DEMO.TXT(README)'": EDC5003I Truncation of a record occurred during an I/O operation.
But anyway, thanks a lot for being so responsive and helpful. I'm making my first steps with git on z/OS and i still have a lot to learn.... ;-)

**Comment by zorts** [comment]
Actually, once you get "git pull" working (still waiting for [feedback on the forum](https://forum.rocketsoftware.com/t/using-git-for-z-os-with-github/654/11)), you can pull the changes made in pull request #7 into your repo and the problem should disappear.

**Comment by philippe-richard** [comment]
i cloned it with git windows, and found out that the new  record lenght is 
now a max of 169, which should indeed solve the issue of to_pds.sh
thnaks
(i still have my issue on z/OS with git pull...)


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 67346632 (38 6632)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2 
IBM Client Center, Montpellier WEB Server: http://w3.pssc.mop.ibm.com

=================================================

**Comment by philippe-richard** [comment]
#!/bin/bash 
set -x 
test_setting_gitdir () { 
  GIT_DIR=$(git rev-parse --git-dir) 
   status=$? 
   if [[ $status == 0 ]] ; then 
     echo "GIT_DIR is initially ${GIT_DIR}" 
    if test -n "$GIT_DIR"; then 
       GIT_DIR=$(cd "$GIT_DIR" && pwd) 
       echo "GIT_DIR was changed to $GIT_DIR" 
     else 
       echo "GIT_DIR was empty" 
     fi 
   else 
     echo "It looks like git rev-parse --git-dir failed" 
   fi 
 } 
 test_setting_gitdir 

. test1.sh
. test1.sh
+ . test1.sh
++ set -x
++ test_setting_gitdir
+++ git rev-parse --git-dir
++ GIT_DIR=$'\056\147\151\164\012'
++ status=0
++ [[ 0 == 0 ]]
++ echo 'GIT_DIR is initially ÅÑÈ'
GIT_DIR is initially ÅÑÈ
++ test -n $'\056\147\151\164\012'
+++ cd $'\056\147\151\164\012'
bash: cd: ÅÑÈ: EDC5129I No such file or directory.
++ GIT_DIR=
++ echo 'GIT_DIR was changed to '
GIT_DIR was changed to

=================
but if i enter git rev-parse --git-dir , then i get a good result back
+ git rev-parse --git-dir
.git
=====================
env | grep GIT
+ env
+ grep GIT
GIT_SHELL=/usr/local/bin/bash
GIT_TEMPLATE_DIR=/usr/local/share/git-core/templates
GIT_EXEC_PATH=/usr/local/libexec/git-core
SPARKID:/u/sparkid/hello_world/hello_world/hello_world: >env | grep CVT
+ env
+ grep CVT
_BPXK_AUTOCVT=ON
_CEE_RUNOPTS=FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
=================================

do we have any sort opf translation problem ?


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 67346632 (38 6632)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2 
IBM Client Center, Montpellier WEB Server: http://w3.pssc.mop.ibm.com

=================================================
