### ISSUE TITLE
git-sh-setup: line 342

### ISSUE THREAD

**Issue by philippe-richard** [zorts/hello_world#8]
When i issue git push or git pull commands, i get
>git pull origin mybranch           /usr/local/libexec/git-core/git-sh-setup: line 342: cd: ÅÑÈ: EDC5129I No such file or directory.
line 342 in the script shows:
 BROWSE    /Z22R01/usr/local/libexec/git-core/git-s Line 0000000342 Col
.test -n "$GIT_DIR" && GIT_DIR=$(cd "$GIT_DIR" && pwd) || {            
..echo >&2 "Unable to determine absolute path of git directory"        

is there any issue with $GIT_DIR ?

**Comment by zorts** [comment]
This issue is with the z/OS port of git, not this repo. See: https://forum.rocketsoftware.com/t/using-git-for-z-os-with-github/654/10
